### ISSUE TITLE
怎么投票啊

### ISSUE THREAD

**Issue by eventlOwOp** [werewoif-dev/nodejs-bot#3]
私发vote和群里发vote也都没有用,
发的时`vote <player>`
控制台也没有任何报错和信息

**Comment by eventlOwOp** [comment]
补充一下, 私发会提示没有投票权限, 群里发没有反应![](//啧.tk/kel)

**Comment by memset0** [comment]
怎么还真有人用这傻逼项目啊

**Comment by memset0** [comment]
退役前写的现在懒得管了

**Comment by memset0** [comment]
但是vote应该是好的单元测试都跑过了

**Comment by eventlOwOp** [comment]
![](//啧.tk/kel)但是我这里好像测试跑不过, 不知道什么原因
